name: Test

on:
    push:
        branches:
            - master
    pull_request:

env:
    NODE_OPTIONS: --experimental-vm-modules

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node_version: [ 18, 20 ]
                prettier_version: [ "^2.3.0", "^3.0.0" ]
                eslint_plugin_prettier_version: [ "^4.0.0", "^5.0.0" ]
                exclude:
                    -   prettier_version: ^2.3.0
                        eslint_plugin_prettier_version: ^5.0.0
                    -   prettier_version: ^3.0.0
                        eslint_plugin_prettier_version: ^4.0.0
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ matrix.node_version }}
                    cache: "yarn"

            -   name: Install Prettier
                run: yarn add prettier@${{ matrix.prettier_version }}

            -   name: Install Eslint plugin for prettier
                run: yarn add --dev eslint-plugin-prettier@${{ matrix.eslint_plugin_prettier_version }}

            -   name: Run Test
                run: yarn test
